a=[45,65,84,37,90,95,78,83,99,89,53]
# # # a=[78,22,33,45,26,13,32]
# i=0
# max=0
# m2=0
# m3=0
# while i<len(a):
#     j=0
#     while j<len(a):
#         if a[j]>max:
#             max=a[j]
#         elif a[j]>m2 and a[j]!=max:
#             m2=a[j]
#         elif   a[j]>m3 and a[j]!=max and a[j]!=m2  :
#             m3=a[j]
#         j+=1
#     i+=1    
# print(max, m2,m3)
# # print(m2)
# print(m3)